// SPDX-FileCopyrightText: 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
//
// SPDX-License-Identifier: Apache-2.0

#ifndef ASTL_API_COUNTER_H_
#define ASTL_API_COUNTER_H_

#include <string>

#include "astl/astl.h"
#include "common/capabilities.hpp"
#include "common/metric_config.hpp"
#include "metric/i_counter.hpp"
#include "operation/operation.hpp"

namespace astl {

/**
 * @brief Implementation of a astl_counter_handle_t on a specific target
 *        This class implements the ICounter interface and extends RawMetric to provide
 *        basic direct counter reading. Since ICounter derives from IMetric, we have some
 *        multiple inheritance w/ the diamond problem, so we explicitly implement some methods to call RawMetric
 *
 */
class Counter : public RawMetric, public virtual ICounter {
 public:
  /**
   * @brief Initialize this counter instance with configuration and target
   */
  explicit Counter(const MetricConfig *config, const ITarget *target);

  /**
   * @brief Check if the Capabilities are met for this metric.
   * This method can be overridden by derived classes to implement specific capability checks.
   *
   * @param capabilities The capabilities to check against.
   * @return true if the capabilities are met, false otherwise.
   */
  auto CheckCapabilities(const Capabilities &capabilities) const -> bool override {
    return RawMetric::CheckCapabilities(capabilities);
  };

  /**
   * @brief Get the Operations required to sample the counter.
   * The operations are used by the collector manager to determine what collector to be used and what samples are
   * collected.
   *
   * @return OperationSequence
   */
  auto GetOperations() -> std::expected<OperationSequence, astl_status_code> override;

  /**
   * @brief Receive a single raw sample for this counter.
   *
   * @param sample Raw sample produced by a collector operation.
   * @return ASTL_STATUS_SUCCESS on success or an error code (e.g. ASTL_STATUS_METRIC_RECEIVED_INVALID_SAMPLE).
   */
  auto ReceiveRawSample(const RawSampledData &sample) -> astl_status_code override;

  /**
   * @brief Set the destination sink for processed samples generated by this counter.
   *
   * Thread-safety: Should be called during initialization before concurrent sampling begins.
   * Passing nullptr disables forwarding (samples may still be internally stored / summarized).
   *
   * @param processed_sample_sink Sink implementing IProcessedSampleSink to receive processed samples.
   */
  auto SetProcessedSampleSink(IProcessedSampleSink *processed_sample_sink) -> void override {
    RawMetric::SetProcessedSampleSink(processed_sample_sink);
  }

  /**
   * @brief Reset the counter state discarding all processed samples and internal accumulators.
   */
  auto Reset() -> void override;

  /**
   * @brief Produce any final derived values / summaries for this counter.
   *
   * Called after raw sampling has completed. Part of satisfying the IMetric interface,
   * but not really needed or implemented in a meaningful way in Counter.
   *
   * @return ASTL_STATUS_SUCCESS unconditionally
   */
  auto Summarize() -> astl_status_code override { return ASTL_STATUS_SUCCESS; };

  /**
   * @brief Assign values such as name, units, etc to the given properties pointer.
   * @param properties Non-null pointer to structure to populate.
   * @return ASTL_STATUS_SUCCESS or ASTL_STATUS_BAD_ARGUMENT.
   */
  auto GetProperties(astl_metric_properties_t *properties) const -> astl_status_code override {
    return RawMetric::GetProperties(properties);
  };

  /**
   * @brief Retrieve the Counter's name.
   */
  auto Name() const -> std::string const & override { return RawMetric::Name(); };

  /**
   * @brief Assign values such as name, units, etc to the given properties pointer.
   */
  auto GetProperties(astl_counter_properties_t *properties) const -> astl_status_code override;

  /** Note that GetProperties(astl_metric_properties_t) is implemented final in RawMetric */

  /**
   * @brief Forward a single processed sample to the registered sink (if any).
   *
   * Convenience wrapper used by derived metrics after constructing a processed sample.
   *
   * @param processed_sample Sample to forward.
   * @return ASTL_STATUS_SUCCESS or a status from the sink dispatch.
   */
  auto SinkProcessedSample(const ProcessedSampledData &processed_sample) -> astl_status_code override {
    return RawMetric::SinkProcessedSample(processed_sample);
  }

 private:
  // note we have a MetricConfig base class members _configuration and _targetfrom RawMetric
};

}  // namespace astl

#endif  // ASTL_API_COUNTER_H_
