// SPDX-FileCopyrightText: 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
//
// SPDX-License-Identifier: Apache-2.0

#ifndef RAW_METRIC_HPP_
#define RAW_METRIC_HPP_

#include <cctype>
#include <string>

#include "astl/astl.h"
#include "astl_logger.hpp"
#include "common/metric_config.hpp"
#include "i_metric.hpp"
#include "i_processed_sample_sink.hpp"
#include "i_raw_sample_sink.hpp"

namespace astl {
/**
 * @brief Base class for raw metric types that process sampled data.
 *
 * RawMetric provides default behavior for capability checking and operation setup.
 * Specific metric types like sampled, delta, or residency should inherit from this class
 * and implement sample processing and summarization.
 */
class RawMetric : public virtual IMetric {
 public:
  ~RawMetric() override = default;

  RawMetric()                  = delete;  // Default constructor is deleted to prevent instantiation without parameters.
  RawMetric(const RawMetric &) = delete;
  RawMetric &operator=(const RawMetric &) = delete;
  RawMetric(RawMetric &&)                 = delete;
  RawMetric &operator=(RawMetric &&)      = delete;

  /**
   * @brief Construct a RawMetric with specified name, description, units, and value type.
   *
   * @param configuration The configuration for the metric, including name, units, and how to build operations
   * @param target The telemetry source for this metric instance
   * @param processed_sample_sink Output for where processed samples should be sent
   */
  explicit RawMetric(const MetricConfig *configuration, const ITarget *target,
                     IProcessedSampleSink *processed_sample_sink);

  /**
   * @brief Check if the Capabilities are met for this metric.
   * This method can be overridden by derived classes to implement specific capability checks.
   *
   * @param capabilities The capabilities to check against.
   * @return true if the capabilities are met, false otherwise.
   */
  auto CheckCapabilities(const Capabilities &capabilities) const -> bool override;

  /**
   * @brief Get the Operations required to the metric.
   * The API determine the collector protocol from the Metric Config and create the Operations.
   *
   * @return OperationSequence
   */
  auto GetOperations() -> std::expected<OperationSequence, astl_status_code> override;

  /**
   * @brief Receive a single normalized sample for this metric.
   *
   * Implementations should validate the sample (type, ordering constraints, etc.), update
   * any internal accumulation state, optionally log it (via LogNormalizedSample), and when appropriate
   * emit one or more processed samples to the registered processed sample sink.
   *
   * @param sample Normalized sample (CLOCK_MONOTONIC_RAW timestamp, ns resolution).
   * @return ASTL_STATUS_SUCCESS on success or an error code (e.g. ASTL_STATUS_METRIC_RECEIVED_INVALID_SAMPLE).
   */
  auto ReceiveRawSample(const NormalizedSampledData &sample) -> astl_status_code override = 0;

  /**
   * @brief Set the destination sink for processed samples generated by this metric.
   *
   * Thread-safety: Should be called during initialization before concurrent sampling begins.
   * Passing nullptr disables forwarding (samples may still be internally stored / summarized).
   *
   * @param processed_sample_sink Sink implementing IProcessedSampleSink to receive processed samples.
   */
  auto SetProcessedSampleSink(IProcessedSampleSink *processed_sample_sink) -> void override;

  /**
   * @brief Reset the metric state discarding all processed samples and internal accumulators.
   */
  auto Reset() -> void override = 0;

  /**
   * @brief Produce any final derived values / summaries for this metric.
   *
   * Called after raw sampling has completed. Implementations may generate additional processed samples
   * (e.g. final averages) or compute summary statistics for external reporting.
   *
   * @return ASTL_STATUS_SUCCESS on success or an error code indicating summarization failure.
   */
  auto Summarize() -> astl_status_code override = 0;

  /**
   * @brief Assign values such as name, units, etc to the given properties pointer.
   * @param properties Non-null pointer to structure to populate.
   * @return ASTL_STATUS_SUCCESS or ASTL_STATUS_BAD_ARGUMENT.
   */
  auto GetProperties(astl_metric_props_t *properties) const -> astl_status_code override;

  /**
   * @brief Retrieve the metric's name.
   */
  auto Name() const -> std::string const & override;
  /**
   * @brief Retrieve the metric's stable internal identifier.
   */
  auto Id() const -> std::string const & override;

  /**
   * @brief Forward a single processed sample to the registered sink (if any).
   *
   * Convenience wrapper used by derived metrics after constructing a processed sample.
   *
   * @param processed_sample Sample to forward.
   * @return ASTL_STATUS_SUCCESS or a status from the sink dispatch.
   */
  auto SinkProcessedSample(const ProcessedSampledData &processed_sample) -> astl_status_code override;

  /**
   * @brief Log the pause event for this metric and return success.
   *
   * Overrides the no-op default in IMetric so that RawMetric (and all derived
   * metric types) emit a diagnostic log entry whenever collection is paused.
   *
   * @param pause_timestamp CLOCK_MONOTONIC_RAW timestamp associated with the pause event.
   * @return ASTL_STATUS_SUCCESS.
   */
  auto ProcessPauseSample(ProcessedSampleTimestamp pause_timestamp) -> astl_status_code override;

 protected:
  /**
   * @brief Validate that the sample's value type matches this metric's expected input type.
   * @param sample Normalized sample to validate.
   * @return ASTL_STATUS_SUCCESS if types match; ASTL_STATUS_METRIC_RECEIVED_INVALID_SAMPLE otherwise.
   */
  auto CheckSampleValueType(const NormalizedSampledData &sample) const -> astl_status_code;

  /**
   * @brief Log a normalized sample to the raw sample logger (CSV format).
   * @param sample Normalized sample to log.
   */
  auto LogNormalizedSample(const NormalizedSampledData &sample) -> void;

  /**
   * @brief Apply configured scaling and formula to produce a processed value.
   *
   * Scaling is represented as a formula step inside AnyFormula (possibly a FormulaPipeline),
   * so RawMetric always uses a single formula application path.
   *
   * @param raw_value The raw sample value to process
   * @return Processed AstlValue if formula application succeeds, or an error status code
   */
  auto ApplyFormula(const AstlValue &raw_value) const -> std::expected<AstlValue, astl_status_code>;

  /**
   * @brief Sanitize a metric name for use as a filename.
   * @param name Original metric name.
   * @return Sanitized string safe for filesystem use.
   */
  static auto SanitizeMetricNameForFilename(const std::string &name) -> std::string;

  // Member variables for metrics are protected to allow access in derived classes.
  // NOLINTBEGIN - Disable clang-tidy checks for protected members.
  // The common parameters used by all metric types (formula, target, sink wiring) go in here.

  // non-owned pointer to the configuration for this metric (owned by the MetricHandle)
  MetricConfig const *_configuration;

  const ITarget *_target;  // placeholder for a target needed for syncing the samples back to the correct target. TODO:
                           // target is not needed by the metric instances for any other reason other than maybe logger.
                           // Find way to get ride of it by maybe adding a separate sink between metric instances to the
                           // metric manager and the metric manager to the orchestrator

  mutable std::mutex _metric_mutex;  // prevent the processed samples syncing to be done by two threads at once

  IProcessedSampleSink *_processed_sample_sink =
      nullptr;  //!< The (optional) destination for where processed data should be sent

  // Create a Logger instance explicitly to log raw samples
  // TODO (ASTL-58): When the output manager is implemented raw_sample_logger will be part of the OutputManager.
  astl::Logger _raw_sample_logger{astl::LogLevel::Info, false /* Console logging disabled */,
                                  false /* No default formatting */, "raw_samples.csv"};

  // NOLINTEND - End of clang-tidy checks for protected members.
};  // End of RawMetric class

}  // namespace astl

#endif  // RAW_METRIC_HPP_
