/*******************************************************************************
 * SPDX-FileCopyrightText: Copyright (C) 2025 Arm Limited and/or its affiliates
 * SPDX-FileCopyrightText: <open-source-office@arm.com>
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy
 * of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations
 * under the License.
 ******************************************************************************/

#ifndef RAW_METRIC_HPP_
#define RAW_METRIC_HPP_

#include <algorithm>
#include <cctype>
#include <span>
#include <string>

#include "astl/astl.h"
#include "astl_logger.hpp"
#include "i_metric.hpp"
#include "i_processed_sample_sink.hpp"
#include "i_raw_sample_sink.hpp"

namespace astl {

/**
 * @brief Base class for raw metric types that process sampled data.
 *
 * RawMetric provides default behavior for capability checking and operation setup.
 * Specific metric types like sampled, delta, or residency should inherit from this class
 * and implement sample processing and summarization.
 */
class RawMetric : public IMetric {
 public:
  ~RawMetric() override = default;

  RawMetric()                  = delete;  // Default constructor is deleted to prevent instantiation without parameters.
  RawMetric(const RawMetric &) = delete;
  RawMetric &operator=(const RawMetric &) = delete;
  RawMetric(RawMetric &&)                 = delete;
  RawMetric &operator=(RawMetric &&)      = delete;

  /**
   * @brief Construct a RawMetric with specified name, description, units, and value type.
   *
   * @param name The name of the metric.
   * @param description A brief description of the metric.
   * @param units The units of measurement for this metric.
   * @param value_type The type of values this metric will process.
   */
  explicit RawMetric(const char *name, const char *description, astl_units_t units, astl_value_type_t value_type,
                     astl_metric_type_t metric_type, const ITarget *target, IProcessedSampleSink *processed_sample_sink)
      : _name(name),
        _description(description),
        _units(units),
        _value_type(value_type),
        _metric_type(metric_type),
        _target(target) {
    SetProcessedSampleSink(processed_sample_sink);
    if (!_processed_sample_sink) {
      ASTL_LOG_ERROR("No processed sample sink set for metric '{}'. Sample will be dropped.", _name);
    }

    // Initialize logger header
    // TODO (ASTL-58): When the output manager is implemented raw_sample_logger will be part of the OutputManager.
    _raw_sample_logger.LogInfo("Metric, Description, Units, Raw-Value, Timestamp \n");
  }

  /**
   * @brief Check if the Capabilities are met for this metric.
   * This method can be overridden by derived classes to implement specific capability checks.
   *
   * @param capabilities The capabilities to check against.
   * @return true if the capabilities are met, false otherwise.
   */
  bool CheckCapabilities(const Capabilities &capabilities) const override {
    (void)capabilities;
    return true;  // Default implementation, can be overridden by derived classes
  }

  /**
   * @brief Get the Operations required to the metric.
   * The API determine the collector protocol from the Metric Config and create the Operations.
   *
   * @return OperationSequence
   */
  std::expected<OperationSequence, astl_status_code> GetOperations() override {
    // Default implementation returns an empty sequence
    return OperationSequence{};
  }

  /**
   * @brief Receive a single raw sample for this metric.
   *
   * Implementations should validate the sample (type, ordering constraints, etc.), update
   * any internal accumulation state, optionally log it (via LogRawSample), and when appropriate
   * emit one or more processed samples to the registered processed sample sink.
   *
   * @param sample Raw sample produced by a collector operation.
   * @return ASTL_STATUS_SUCCESS on success or an error code (e.g. ASTL_STATUS_METRIC_RECEIVED_INVALID_SAMPLE).
   */
  astl_status_code ReceiveRawSample(const RawSampledData &sample) override = 0;

  /**
   * @brief Set the destination sink for processed samples generated by this metric.
   *
   * Thread-safety: Should be called during initialization before concurrent sampling begins.
   * Passing nullptr disables forwarding (samples may still be internally stored / summarized).
   *
   * @param processed_sample_sink Sink implementing IProcessedSampleSink to receive processed samples.
   */
  void SetProcessedSampleSink(IProcessedSampleSink *processed_sample_sink) final;

  /**
   * @brief Return a read-only view over processed samples accumulated by this metric.
   *
   * The returned span remains valid until the next mutating operation (e.g. additional ReceiveRawSample,
   * Reset, Summarize) alters the underlying container.
   */
  std::span<const ProcessedSampledData> GetProcessedSamples() const override = 0;

  /**
   * @brief Reset the metric state discarding all processed samples and internal accumulators.
   */
  void Reset() override = 0;

  /**
   * @brief Produce any final derived values / summaries for this metric.
   *
   * Called after raw sampling has completed. Implementations may generate additional processed samples
   * (e.g. final averages) or compute summary statistics for external reporting.
   *
   * @return ASTL_STATUS_SUCCESS on success or an error code indicating summarization failure.
   */
  astl_status_code Summarize() override = 0;

  /**
   * @brief Assign values such as name, units, etc to the given properties pointer.
   * @param properties Non-null pointer to structure to populate.
   * @return ASTL_STATUS_SUCCESS or ASTL_STATUS_BAD_ARGUMENT.
   */
  astl_status_code GetProperties(astl_metric_properties_t *properties) const final;

  /**
   * @brief Retrieve the metric's name.
   */
  auto Name() const -> std::string const & override { return _name; }

  /**
   * @brief Forward a single processed sample to the registered sink (if any).
   *
   * Convenience wrapper used by derived metrics after constructing a processed sample.
   *
   * @param processed_sample Sample to forward.
   * @return ASTL_STATUS_SUCCESS or a status from the sink dispatch.
   */
  astl_status_code SinkProcessedSample(const ProcessedSampledData &processed_sample) final;

 protected:
  /**
   * @brief Validate that the raw sample's value type matches this metric's expected type.
   * @param raw_sample Raw sample to validate.
   * @return ASTL_STATUS_SUCCESS if types match; ASTL_STATUS_METRIC_RECEIVED_INVALID_SAMPLE otherwise.
   */
  astl_status_code CheckSampleValueType(const RawSampledData &raw_sample) const;

  /**
   * @brief Log a raw sample to the raw sample logger (CSV format).
   * @param raw_sample Sample to log.
   */
  void LogRawSample(const RawSampledData &raw_sample);

  /**
   * @brief Sanitize a metric name for use as a filename.
   * @param name Original metric name.
   * @return Sanitized string safe for filesystem use.
   */
  static std::string SanitizeMetricNameForFilename(const std::string &name);

  // Member variables for metrics are protected to allow access in derived classes.
  // NOLINTBEGIN - Disable clang-tidy checks for protected members.
  // The common parameters used by all metric types like formula, mask go in here.
  std::string        _name;
  std::string        _description;
  astl_units_t       _units;
  astl_value_type_t  _value_type;
  astl_metric_type_t _metric_type;

  const ITarget *_target;  // placeholder for a target needed for syncing the samples back to the correct target. TODO:
                           // target is not needed by the metric instances for any other reason other than maybe logger.
                           // Find way to get ride of it by maybe adding a separate sink between metric instances to the
                           // metric manager and the metric manager to the orchestrator

  mutable std::mutex _metric_mutex;  // prevent the processed samples syncing to be done by two threads at once

  IProcessedSampleSink *_processed_sample_sink =
      nullptr;  //!< The (optional) destination for where processed data should be sent

  // Create a Logger instance explicitly to log raw samples
  // TODO (ASTL-58): When the output manager is implemented raw_sample_logger will be part of the OutputManager.
  astl::Logger _raw_sample_logger{astl::LogLevel::Info, false /* Console logging disabled */,
                                  false /* No default formatting */, "raw_samples.csv"};

  // NOLINTEND - End of clang-tidy checks for protected members.
};  // End of RawMetric class

}  // namespace astl

#endif  // RAW_METRIC_HPP_
