version = 1

# 3rd party licenses
[[annotations]]
path = "**/gplot++.h"
SPDX-FileCopyrightText = "Copyright 2020 Maurizio Tomasi"
SPDX-License-Identifier = "MIT"

# Annotate PR template (because the license header winds up in the PR body if we put it in the .md file)
[[annotations]]
path = ".github/PULL_REQUEST_TEMPLATE.md"
SPDX-FileCopyrightText = "Copyright (C) 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>"
SPDX-License-Identifier = "Apache-2.0"

# Version file is imported directly to cmake, so don't annotate it in-text
[[annotations]]
path = "VERSION.md"
SPDX-FileCopyrightText = "Copyright (C) 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>"
SPDX-License-Identifier = "Apache-2.0"

# Annotate all .json config files with the Apache-2.0 license
[[annotations]]
path = "**/*.json"
SPDX-FileCopyrightText = "Copyright (C) 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>"
SPDX-License-Identifier = "Apache-2.0"

# documentation
[[annotations]]
path = ["doc/*.pdf", "tools/ATX/doc/*.pdf", "doc/**/*.svg"]
SPDX-FileCopyrightText = "Copyright (C) 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>"
SPDX-License-Identifier = "Apache-2.0"

# Test output files for comparison with expected output, but ignore them for linting
[[annotations]]
path = ["tools/ATX/tests/kernel_tests/**/expected.txt", "tools/mock_scmi/**/**/expected.txt", "tools/scmi_bridge/kernel_tests/**/expected.txt"]
SPDX-FileCopyrightText = "Copyright (C) 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>"
SPDX-License-Identifier = "Apache-2.0"

# Test, demo config
[[annotations]]
path = ["tools/mock_scmi/config/*.csv", "tests/demo/data/*.csv"]
SPDX-FileCopyrightText = "Copyright (C) 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>"
SPDX-License-Identifier = "Apache-2.0"

# function test cases gold files
[[annotations]]
path = "tests/functional/cases/atx/**/*.gold"
SPDX-FileCopyrightText = "Copyright (C) 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>"
SPDX-License-Identifier = "Apache-2.0"

# .astl files are binary. they mostly live in function test cases
[[annotations]]
path = "**/*.astl"
SPDX-FileCopyrightText = "Copyright (C) 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>"
SPDX-License-Identifier = "Apache-2.0"
