# SPDX-FileCopyrightText: 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
#
# SPDX-License-Identifier: Apache-2.0

[metadata]
name = astl
description = Python bindings for Arm SoC Telemetry Library (ASTL)
license = Apache-2.0

[options]
zip_safe = False
packages = find:
python_requires = >=3.10
setup_requires = cython

[options.package_data]
astl = *.pxd

[build_ext]
inplace=0
