#!/usr/bin/env bash

# SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
#
# SPDX-License-Identifier: Apache-2.0

set -eu -o pipefail

function no_leaks() {
	local defect_list_path=$1
	if [ ! -f "${defect_list_path}" ]; then
		echo "❌ Error.  Could not find defect list.  This should have been generated by CMake using the valgrind results" >/dev/stderr
		exit 1
	fi
	grep -F '<DefectList/>' "${defect_list_path}" >/dev/null
	return $?
}

if [ "$#" -ne 1 ]; then
	echo "❌ Error.  Invalid command line usage." >/dev/stderr
	echo "Usage: $0 <ASTL>" >/dev/stderr
	echo "Path to where ASTL is cloned.  This is the directory with the top-level CMakeLists.txt" >/dev/stderr
	exit 1
fi

BUILD_DIR=$1

# Purge old defect lists if they exist to ensure stale results are not consumed.
if [ -d "${BUILD_DIR}/Testing" ]; then
	find "${BUILD_DIR}/Testing" -type f -name DynamicAnalysis.xml -delete
fi

echo "Running Valgrind test shards with up to 4 concurrent processes"
ctest -T memcheck --parallel 4 -L valgrind --test-dir "$BUILD_DIR"

DEFECT_LIST_PATH=$(find "${BUILD_DIR}/Testing" -type f -name DynamicAnalysis.xml -print -quit)

if no_leaks "${DEFECT_LIST_PATH}"; then
	echo "✅ No memory leaks detected"
	exit 0
else
	echo "❌ Error.  Leaks detected.  See ${DEFECT_LIST_PATH}" >/dev/stderr
	exit 1
fi
