#!/usr/bin/env bash

# SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
#
# SPDX-License-Identifier: Apache-2.0

set -eu -o pipefail

function no_leaks() {
	local DEFECT_LIST_PATH=$1
	if [ ! -f "${DEFECT_LIST_PATH}" ]; then
		echo "❌ Error.  Could not find defect list.  This should have been generated by CMake using the valgrind results" >/dev/stderr
		exit 1
	fi
	grep -F '<DefectList/>' "${DEFECT_LIST_PATH}" >/dev/null
	return $?
}

if [ "$#" -ne 1 ]; then
	echo "❌ Error.  Invalid command line usage." >/dev/stderr
	echo "Usage: $0 <ASTL>" >/dev/stderr
	echo "Path to where ASTL is cloned.  This is the directory with the top-level CMakeLists.txt" >/dev/stderr
	exit 1
fi

BUILD_DIR=$1
NUM_THREADS=$(nproc)
DEFECT_LIST_PATH="${BUILD_DIR}/Testing/*/DynamicAnalysis.xml"

# Purge old defect list if it exists to ensure stale results aren't consumed
rm -f "${DEFECT_LIST_PATH}"

echo "Running unit tests in parallel with ${NUM_THREADS} threads"
ctest -T memcheck --parallel "${NUM_THREADS}" --test-dir "$BUILD_DIR"

if no_leaks "${DEFECT_LIST_PATH}"; then
	echo "✅ No memory leaks detected"
	exit 0
else
	echo "❌ Error.  Leaks detected.  See ${DEFECT_LIST_PATH}" >/dev/stderr
	exit 1
fi
