set(ATL_CMAKE_MACRO_DIR ${CMAKE_CURRENT_LIST_DIR}/../.. CACHE INTERNAL "")

macro(SetAtlVersion)
  file(STRINGS "${ATL_CMAKE_MACRO_DIR}/VERSION.md" ATL_VERSION)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DATL_VERSION=${ATL_VERSION}")
endmacro()

