set(ASTL_CMAKE_MACRO_DIR ${CMAKE_CURRENT_LIST_DIR}/../.. CACHE INTERNAL "")

macro(SetAstlVersion)
  file(STRINGS "${ASTL_CMAKE_MACRO_DIR}/VERSION.md" ASTL_VERSION)
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -DASTL_VERSION=${ASTL_VERSION}")
endmacro()

