name: Lint

permissions:
  contents: read
  checks: write

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      # Set fail-fast to true to terminate the jobs as soon as any one fails. set to false for debug
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        cmake_preset: [debug]

    env:
      # Indicates the location of the vcpkg as a Git submodule of the project repository.
      # Not using "VCPKG_ROOT" because a variable with the same name is defined in the VS's
      # Developer Command Prompt environment in VS 2022 17.6, which would override this one
      # if it had the same name.
      _VCPKG_: ${{ github.workspace }}/external/vcpkg
      # Tells vcpkg where binary packages are stored.
      VCPKG_DEFAULT_BINARY_CACHE: ${{ github.workspace }}/external/vcpkg/bincache
      # Let's use GitHub Action cache as storage for the vcpkg Binary Caching feature.
      VCPKG_BINARY_SOURCES: "clear;x-gha,readwrite"

    steps:
      # Set env variables needed for vcpkg to use GitHub Action cache for dependencies
      - name: 🌱 Set env vars
        uses: actions/github-script@v8
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');

      - name: ⤵️ Checkout code
        uses: actions/checkout@v5
        with:
          # fetch all history so we can git diff for clang-tidy relevant files
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true

      - name: ⤵️ Install Tools (ubuntu-latest)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format-20 cppcheck cmake yamllint libsensors-dev
          sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-20 200

      - name: 📂 VCPKG - Create VCPKG_DEFAULT_BINARY_CACHE directory
        run: mkdir -p $VCPKG_DEFAULT_BINARY_CACHE
        shell: bash

      # Restore vcpkg from the GitHub Action cache service. Note that packages are restored by vcpkg's binary caching
      # when it is being run afterwards by CMake.
      - name: ⤵️ VCPKG - Restore Cache
        uses: actions/cache@v4
        with:
          # The first path is the location of vcpkg: it contains the vcpkg executable and data files, as long as the
          # built package archives (aka binary cache) which are located by VCPKG_DEFAULT_BINARY_CACHE env var.
          # The other paths starting with '!' are exclusions: they contain temporary files generated during the build of the installed packages.
          path: |
            ${{ env._VCPKG_ }}
            !${{ env._VCPKG_ }}/buildtrees
            !${{ env._VCPKG_ }}/packages
            !${{ env._VCPKG_ }}/downloads
            !${{ env._VCPKG_ }}/installed
          # The key is composed in a way that it gets properly invalidated whenever a different version of vcpkg is being used.
          key: |
            os-${{ matrix.os }}-${{ hashFiles( '.git/modules/vcpkg/HEAD' )}}-vcpkg.json

      - name: ⤵️ VCPKG - Install Dependencies
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: "${{ github.workspace }}/external/vcpkg"
          vcpkgJsonGlob: "**/vcpkg.json"

      - name: ⚙️ CMake - Configure
        # Configure CMake in a 'build' subdirectory.
        run: >
          cmake
          -DCMAKE_CXX_COMPILER=clang
          -DCMAKE_C_COMPILER=clang
          -DENABLE_VALGRIND=OFF
          -S ${{ github.workspace }}
          --preset ${{ matrix.cmake_preset }}

      - name: 🧹 YAML Lint
        if: matrix.os == 'ubuntu-latest'
        run: yamllint ${{ github.workspace }}/.github/workflows/*.yaml

      - name: 🧹 Check Formatting
        run: ${{ github.workspace }}/scripts/check_format.sh

      - name: 🧹 Lint with cppcheck
        run: ${{ github.workspace }}/scripts/cppcheck.sh ${{ github.workspace }}/build/${{ matrix.cmake_preset }}

      - name: 🧹 Lint with clang-tidy
        run: ${{ github.workspace }}/scripts/lint.sh ${{ github.workspace }}/build/${{ matrix.cmake_preset }} pull-request
        env:
          BASE_REF: ${{ github.base_ref }}
          HEAD_REF: ${{ github.head_ref }}
