name: Lint

permissions:
  actions: read
  contents: read
  checks: write

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ${{ matrix.os }}
    strategy:
      # Set fail-fast to true to terminate the jobs as soon as any one fails. set to false for debug
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        cmake_preset: [debug]

    env:
      _VCPKG_: ${{ github.workspace }}/external/vcpkg

    steps:
      - name: ⤵️ Checkout code
        uses: actions/checkout@v5
        with:
          # fetch all history so we can git diff for clang-tidy relevant files
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true

      - name: ⤵️ Install Tools (ubuntu-latest)
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format-20 cppcheck cmake yamllint libsensors-dev
          sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-20 200
          python3 -m pip install --upgrade --user cmakelang

      # Restore per-package vcpkg cache
      - name: ⤵️ VCPKG - Restore Cache
        id: vcpkg-cache
        uses: TAServers/vcpkg-cache@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: ⤵️ VCPKG - Install Dependencies
        uses: lukka/run-vcpkg@v11
        env:
          VCPKG_FEATURE_FLAGS: binarycaching
          VCPKG_BINARY_SOURCES: clear;files,${{ steps.vcpkg-cache.outputs.path }},readwrite
        with:
          vcpkgDirectory: "${{ env._VCPKG_ }}"
          vcpkgJsonGlob: "**/vcpkg.json"

      - name: ⚙️ CMake - Configure
        # Configure CMake in a 'build' subdirectory.
        env:
          VCPKG_FEATURE_FLAGS: binarycaching
          VCPKG_BINARY_SOURCES: clear;files,${{ steps.vcpkg-cache.outputs.path }},readwrite
        run: >
          cmake
          -DCMAKE_CXX_COMPILER=clang
          -DCMAKE_C_COMPILER=clang
          -DENABLE_VALGRIND=OFF
          -S ${{ github.workspace }}
          --preset ${{ matrix.cmake_preset }}

      - name: ⚙️ CMake - Generate Proto Headers
        run: cmake --build --preset ${{ matrix.cmake_preset }} --target proto_gen

      - name: 🧹 YAML Lint
        if: matrix.os == 'ubuntu-latest'
        run: yamllint ${{ github.workspace }}/.github/workflows/*.yaml

      - name: 🧹 Check Formatting
        run: ${{ github.workspace }}/scripts/check_format.sh

      - name: 🧹 Lint with cppcheck
        run: ${{ github.workspace }}/scripts/cppcheck.sh ${{ github.workspace }}/build/${{ matrix.cmake_preset }}

      - name: 🧹 Lint with clang-tidy
        run: ${{ github.workspace }}/scripts/lint.sh ${{ github.workspace }}/build/${{ matrix.cmake_preset }} pull-request
        env:
          BASE_REF: ${{ github.base_ref }}
          HEAD_REF: ${{ github.head_ref }}

      - name: 🧹 Lint with cmakelang
        run: ${{ github.workspace }}/scripts/cmakelang.sh
